### ISSUE TITLE
Question about apiKey

### ISSUE THREAD

**Issue by Apsaliya** [flipkart-incubator/inline-youtube-view#12]
I see apiKey id used to initialise `YouTubePlayerView`. But, Even if I send random string as apiKey to `YouTubeActivity`, videos work fine. Any idea how's that possible?

**Comment by anirudhramanan** [comment]
Is it working in release mode as well ?

**Comment by Apsaliya** [comment]
Yes, Works just fine in release mode as well.

**Comment by anirudhramanan** [comment]
I am assuming it won't work when you publish your app in play store after signing. Btw, this is strange. Let me check and get back to you

**Comment by Apsaliya** [comment]
I went ahead and published my app on play store after I opened this issue. It is working fine there as well.

**Comment by adapana** [comment]
An API key is used when a native player is attached,  In your case, webview is playing video.

**Comment by anirudhramanan** [comment]
closing this
