### ISSUE TITLE
Can't not load video in Youtube Activity

### ISSUE THREAD

**Issue by cchamnab** [flipkart-incubator/inline-youtube-view#21]
`Intent intent = new Intent(GalleryViewerActivity.this, YouTubeActivity.class);
 intent.putExtra("apiKey", API.youtubeKey);
 intent.putExtra("videoId", "zNW9L_1x4IM");
 intent.putExtra("webviewUrl", "https://cdn.rawgit.com/flipkart-incubator/inline-youtube-view/60bae1a1/youtube-android/youtube_iframe_player.html");
startActivity(intent);`

I've provided webViewUrl a default url but it still return  `Web Url is Null`

**Comment by theEpicGunner** [comment]
From which activity are you trying to open this? I do see that in `YouTubeWebViewFragment` that `webViewUrl` is not null so you are getting it.

**Comment by anirudhramanan** [comment]
Key for passing url is `webUrl`. 

Try with 
````
intent.putExtra("webUrl", "https://cdn.rawgit.com/flipkart-incubator/inline-youtube-view/60bae1a1/youtube-android/youtube_iframe_player.html");
````
