### ISSUE TITLE
Please mention in readme that "YouTubeActivity" is needed to be added in manifest

### ISSUE THREAD

**Issue by passiondroid** [flipkart-incubator/inline-youtube-view#5]
I was getting below error - 
Unable to find explicit activity class {com.abc.def/com.flipkart.youtubeview.activity.YouTubeActivity

before i figured out that that YouTubeActivity is required to be added in manifest.
<activity android:name="com.flipkart.youtubeview.activity.YouTubeActivity" />

**Comment by anirudhramanan** [comment]
ah, thanks for reporting. It has been added in the readme file
